name: Build and Deploy Project

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: LD56
  PROJECT_PATH: game/ld56_godot

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      
      - name: Web Build
        run: |
          mkdir -v -p build/web
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "HTML5" ../build/web/index.html
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: build/web

      # - name: Butler Upload
      #   uses: manleydev/butler-publish-itchio-action@master
      #   env:
      #     BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
      #     CHANNEL: web
      #     ITCH_GAME: ${{ secrets.ITCHIO_GAME }}
      #     ITCH_USER: ${{ secrets.ITCHIO_USERNAME }}
      #     PACKAGE: build/web
